version: '3'
services:
  coinking:
    image: hudulgi/coinking
    container_name: coinking
    network_mode: coinking-network
    volumes:
      - '/home/ubuntu/docker/coinking/data:/usr/src/app/data'
      - '/home/ubuntu/docker/coinking/buy_list:/usr/src/app/buy_list'
      - '/home/ubuntu/docker/coinking/config.ini:/usr/src/app/config.ini'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  coinking-server:
    image: hudulgi/coinking-server
    container_name: coinking-server
    network_mode: coinking-network
    volumes:
      - '/home/ubuntu/docker/coinking/data:/usr/src/app/data'
    restart: always
    stdin_open: true
    tty: true